export enum AppCodes {
  // General Success
  SUCCESS = "SUCCESS",
  RESOURCE_CREATED = "RESOURCE_CREATED",
  RESOURCE_UPDATED = "RESOURCE_UPDATED",
  RESOURCE_DELETED = "RESOURCE_DELETED",

  // Authentication
  AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS",
  AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS",
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",
  AUTH_VERIFICATION_EMAIL_SENT = "AUTH_VERIFICATION_EMAIL_SENT",
  AUTH_PASSWORD_RESET_SUCCESS = "AUTH_PASSWORD_RESET_SUCCESS",
  INVALID_EMAIL_OR_TOKEN = "INVALID_EMAIL_OR_TOKEN",
  // Users
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  USER_DELETED = "USER_DELETED",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED",
  USER_VERIFIED = "USER_VERIFIED",
  USER_INACTIVE = "USER_INACTIVE",
  // Validation
  VALIDATION_FAILED = "VALIDATION_FAILED",
  INVALID_INPUT = "INVALID_INPUT",
  MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS",

  // Database
  DATABASE_ERROR = "DATABASE_ERROR",
  DATABASE_CONNECTION_FAILED = "DATABASE_CONNECTION_FAILED",
  DATABASE_QUERY_FAILED = "DATABASE_QUERY_FAILED",

  // External Services
  EXTERNAL_SERVICE_FAILURE = "EXTERNAL_SERVICE_FAILURE",
  PAYMENT_PROVIDER_ERROR = "PAYMENT_PROVIDER_ERROR",

  // Server
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",

  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  PASSWORD_RESET_ATTEMPT_NON_EXISTENT_EMAIL = "PASSWORD_RESET_ATTEMPT_NON_EXISTENT_EMAIL",
  PASSWORD_RESET_ATTEMPT_INVALID_TOKEN = "PASSWORD_RESET_ATTEMPT_INVALID_TOKEN",
  RESEND_VERIFICATION_EMAIL_NON_EXISTENT_EMAIL = "RESEND_VERIFICATION_EMAIL_NON_EXISTENT_EMAIL",

  // Hotels
  HOTEL_NOT_FOUND = "HOTEL_NOT_FOUND",
  HOTEL_DELETED = "HOTEL_DELETED",
  HOTEL_UPDATED = "HOTEL_UPDATED",
  HOTEL_CREATED = "HOTEL_CREATED",
  HOTEL_ALREADY_EXISTS = "HOTEL_ALREADY_EXISTS",
  // Jobs
  JOB_HANDLER_NOT_FOUND = "JOB_HANDLER_NOT_FOUND",
  ACTIVE = "ACTIVE",
  FAILED = "FAILED",
  UNAUTHORIZED = "UNAUTHORIZED",

  //members
  MEMBER_ALREADY_EXISTS = "MEMBER_ALREADY_EXISTS",
  MEMBER_NOT_FOUND = "MEMBER_NOT_FOUND",
  HOTEL_MEMBER_ADDED = "HOTEL_MEMBER_ADDED",
  HOTEL_MEMBER_REMOVED = "HOTEL_MEMBER_REMOVED",
  HOTEL_MEMBER_ROLE_UPDATED = "HOTEL_MEMBER_ROLE_UPDATED",
  ROOMS_RETRIEVED = "ROOMS_RETRIEVED",

  //Room
  ROOM_ALREADY_EXISTS= "ROOM_ALREADY_EXISTS",
  ROOM_NOT_FOUND = "ROOM_NOT_FOUND",
  ROOM_CREATED = "ROOM_CREATED",
  ROOM_DELETED = "ROOM_DELETED",
  ROOM_UPDATED = "ROOM_UPDATED",
  ROOM_RETRIEVED = "ROOM_RETRIEVED",
  ROOMS_DEACTIVATED = "ROOMS_DEACTIVATED",
}
