export enum AppCodes {
  // General Success
  SUCCESS = "SUCCESS",
  RESOURCE_CREATED = "RESOURCE_CREATED",
  RESOURCE_UPDATED = "RESOURCE_UPDATED",
  RESOURCE_DELETED = "RESOURCE_DELETED",

  // Authentication
  AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS",
  AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS",
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",
  AUTH_VERIFICATION_EMAIL_SENT = "AUTH_VERIFICATION_EMAIL_SENT",
  AUTH_PASSWORD_RESET_SUCCESS = "AUTH_PASSWORD_RESET_SUCCESS",
  INVALID_EMAIL_OR_TOKEN = "INVALID_EMAIL_OR_TOKEN",
  // Users
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  USER_DELETED = "USER_DELETED",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED",
  USER_VERIFIED = "USER_VERIFIED",
  USER_INACTIVE = "USER_INACTIVE",
  // Validation
  VALIDATION_FAILED = "VALIDATION_FAILED",
  INVALID_INPUT = "INVALID_INPUT",
  MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS",

  // Database
  DATABASE_ERROR = "DATABASE_ERROR",
  DATABASE_CONNECTION_FAILED = "DATABASE_CONNECTION_FAILED",
  DATABASE_QUERY_FAILED = "DATABASE_QUERY_FAILED",

  // External Services
  EXTERNAL_SERVICE_FAILURE = "EXTERNAL_SERVICE_FAILURE",
  PAYMENT_PROVIDER_ERROR = "PAYMENT_PROVIDER_ERROR",

  // Server
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",

  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  PASSWORD_RESET_ATTEMPT_NON_EXISTENT_EMAIL = "PASSWORD_RESET_ATTEMPT_NON_EXISTENT_EMAIL",
  PASSWORD_RESET_ATTEMPT_INVALID_TOKEN = "PASSWORD_RESET_ATTEMPT_INVALID_TOKEN",
  RESEND_VERIFICATION_EMAIL_NON_EXISTENT_EMAIL = "RESEND_VERIFICATION_EMAIL_NON_EXISTENT_EMAIL",

  // Hotels
  HOTEL_NOT_FOUND = "HOTEL_NOT_FOUND",
  HOTEL_DELETED = "HOTEL_DELETED",
  HOTEL_UPDATED = "HOTEL_UPDATED",
  HOTEL_CREATED = "HOTEL_CREATED",
  HOTEL_ALREADY_EXISTS = "HOTEL_ALREADY_EXISTS",
  HOTEL_ACTIVATED = "HOTEL_ACTIVATED",
  HOTEL_DEACTIVATED = "HOTEL_DEACTIVATED",
  // Jobs
  JOB_HANDLER_NOT_FOUND = "JOB_HANDLER_NOT_FOUND",
  ACTIVE = "ACTIVE",
  FAILED = "FAILED",
  UNAUTHORIZED = "UNAUTHORIZED",

  //members
  MEMBER_ALREADY_EXISTS = "MEMBER_ALREADY_EXISTS",
  MEMBER_NOT_FOUND = "MEMBER_NOT_FOUND",
  HOTEL_MEMBER_ADDED = "HOTEL_MEMBER_ADDED",
  HOTEL_MEMBER_REMOVED = "HOTEL_MEMBER_REMOVED",
  HOTEL_MEMBER_ROLE_UPDATED = "HOTEL_MEMBER_ROLE_UPDATED",
  ROOMS_RETRIEVED = "ROOMS_RETRIEVED",
  JOIN_HOTEL_REQUESTED = "JOIN_HOTEL_REQUESTED",
  JOIN_HOTEL_APPROVED = "JOIN_HOTEL_APPROVED",
  JOIN_HOTEL_REJECTED = "JOIN_HOTEL_REJECTED",

  //Room
  ROOM_ALREADY_EXISTS= "ROOM_ALREADY_EXISTS",
  ROOM_NOT_FOUND = "ROOM_NOT_FOUND",
  ROOM_CREATED = "ROOM_CREATED",
  ROOM_DELETED = "ROOM_DELETED",
  ROOM_UPDATED = "ROOM_UPDATED",
  ROOM_RETRIEVED = "ROOM_RETRIEVED",
  ROOMS_DEACTIVATED = "ROOMS_DEACTIVATED",
  ROOM_UNAVAILABLE = "ROOM_UNAVAILABLE",

  //Guest
  GUEST_CREATED = "GUEST_CREATED",
  GUEST_NOT_FOUND = "GUEST_NOT_FOUND",
  GUEST_ALREADY_EXISTS = "GUEST_ALREADY_EXISTS",
  GUESTS_RETRIEVED = "GUESTS_RETRIEVED",
  GUEST_UPDATED = "GUEST_UPDATED",
  GUEST_DELETED = "GUEST_DELETED",

  //Booking
  BOOKING_CREATED = "BOOKING_CREATED",
  BOOKING_NOT_FOUND = "BOOKING_NOT_FOUND",
  BOOKING_CONFLICT = "BOOKING_CONFLICT",
  BOOKING_UPDATED = "BOOKING_UPDATED",
  BOOKING_DELETED = "BOOKING_DELETED",
  BOOKING_CANCELLED = "BOOKING_CANCELLED",

  
  INVALID_OPERATION = "INVALID_OPERATION",
  // Payments
  PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED",
  PAYMENTS_RETRIEVED = "PAYMENTS_RETRIEVED",
  PAYMENT_RETRIEVED = "PAYMENT_RETRIEVED",
  PAYMENTS_FOR_BOOKING_RETRIEVED = "PAYMENTS_FOR_BOOKING_RETRIEVED",
  PAYMENT_CREATED = "PAYMENT_CREATED",
  PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND",
  PAYMENT_VERIFIED = "PAYMENT_VERIFIED",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  ONLINE_PAYMENT_INITIALIZED = "ONLINE_PAYMENT_INITIALIZED",
  ONLINE_PAYMENT_VERIFIED = "ONLINE_PAYMENT_VERIFIED",
  ONLINE_PAYMENT_CONFIRMATION_FAILED = "ONLINE_PAYMENT_CONFIRMATION_FAILED",
  ONLINE_PAYMENT_CONFIRMED = "ONLINE_PAYMENT_CONFIRMED",

}
